### ISSUE TITLE
Update license

### ISSUE THREAD

**Issue by oleg-andreyev** [ecentria/JsonApiBundle#3]
We need to add MIT license file or remove it from `composer.json`

Example: https://github.com/symfony/symfony/blob/master/LICENSE

Ref.: https://en.wikipedia.org/wiki/MIT_License

**Comment by dbalabka** [comment]
@oleg-andreyev please see https://github.com/koemeet/JsonApiBundle/issues/42

**Comment by dbalabka** [comment]
koemeet#42 is resolved. License is [MIT](https://opensource.org/licenses/MIT). It is not obvious but file sits here:
https://github.com/ecentria/JsonApiBundle/blob/master/Resources/meta/LICENSE

It is not modified.
